# Generated by Django 4.0.4 on 2022-05-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.IntegerField(choices=[[0, 'ninguno'], [1, 'Cuerdas'], [2, 'Percusión'], [3, 'Amplificadores'], [4, 'Accesorios']], null=True),
        ),
    ]
