# Generated by Django 4.0.4 on 2022-05-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('puesto', models.IntegerField(choices=[[0, 'Administrador'], [1, 'Bodeguero'], [2, 'Vendedor'], [3, 'Contador']])),
            ],
        ),
    ]
