# Generated by Django 4.0.4 on 2022-05-16 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VistaEmpleados', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='nickname',
            new_name='username',
        ),
    ]
