# Generated by Django 4.0.4 on 2022-05-09 21:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_producto', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=30)),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('valor', models.IntegerField()),
            ],
        ),
    ]
