# Generated by Django 4.0.4 on 2022-05-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiProductos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
