# Generated by Django 4.0.4 on 2022-05-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=100)),
                ('valor', models.IntegerField()),
                ('imagen', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=100)),
                ('valorTotal', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
                ('productoCarrito', models.ManyToManyField(to='vistaCliente.productocarrito')),
            ],
        ),
    ]
